### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [39takagikouta/graduation_exam#63]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. フレームワークの特性を活かし冗長なコードを書いていないか
3. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
確認しました。LGTMです。

## フレームワークの特性を活かし冗長なコードを書いていないか
気になった箇所を一部挙げたのでご確認ください。
- alarms#mypageなどにある「where...」等、scopeやクラスメソッドにしましょう。
- インデントのズレ。Rubocopを通してください。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
気になった箇所を挙げたのでご確認ください。
- 動画が枠内からはみ出す画面サイズがあったので一度確認してください。
- メールアドレスの編集・更新ができるようにする
- 動画のURLを登録しない。オススメ動画が出てくるようにする
- メールアドレスでの会員登録後、LINEと紐付けられるようにする。（現状別ユーザーとして認識される）

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
よろしくお願いいたします。

**Comment by 39takagikouta** [comment]
土屋講師、ご対応いただきありがとうございました！
レビュー内容について、承知しました！
「動画のURLを登録しない。オススメ動画が出てくるようにする」というご指摘は、動画のurl登録時にフォームの下部におすすめ動画を数件表示するといった認識であっていますでしょうか？
よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
任意登録ですが、お笑い以外の動画が投稿できてしまったり、そもそもユーザーにURLを打ち込ませるということは、その動画を視聴する機会を設定時に与えてしまうので、このサービスの根幹である「起きられたときの報酬」度合いが低下してしまっていると考えます。

URLの登録が無い場合は登録済み？の動画が選択されるようなので、ユーザーの登録した趣向性やお気に入りのお笑いなどからYouTube APIに投げて、ユーザーがURLを登録しなくてもオススメな動画が提示されるようにした方が良いのではないかとの意見が出ておりました。

上記ご確認の上、引き続き開発を頑張ってください。

**Comment by 39takagikouta** [comment]
ご対応ありがとうございます。
なるほど、確かにおっしゃる通りです。
現状、URLの登録がない場合はユーザーの登録した嗜好性からyoutube APIで検索して、viewedvideosテーブルに登録されていないものの中で一番最初にヒットした動画を表示しているのですが、アラーム登録のページでもおすすめ動画をいくつか登録し、その中から選べるようにしたいと思います。
ありがとうございます、頑張ります！
