### ISSUE TITLE
Power Up vol.01

### ISSUE THREAD

**Issue by Tsuchiya2** [39takagikouta/graduation_exam#75]
MVPレビューお疲れ様でした。
これから就活に向けて、webアプリをパワーアップしていきましょう！

- MVPレビューでも書きましたが、ユーザーに動画のURLを打ち込ませるのを廃止して、お笑いの嗜好性から報酬となる動画を自動で選択されるようにしてください。
- 早起き一覧をクリックすると、みんなの起床成功情報が表示されるのに違和感を感じました。また、お笑いの動画もみんなの起床成功情報で閲覧できてしまうので、報酬性が低下してしまっています。早起き一覧の方向で進むのであれば、早起きに成功した目に見えて実感できるようなページに変更してください。他の人の起床成功情報を表示するのであれば、競争心がくすぐられるor自分も継続して頑張ろうと思えるページに変更してください。（どちらもどうするか一度考えてみてください）
- マイページからアラームを設定する箇所ですが、1日ずつしか登録できないのは不便ですので、一括での登録・個々の編集はカレンダーの文字列をクリックすると編集画面へ遷移できるようにしてください。マイページの文言表示の部分は変更に伴って修正した方が良くなってくるかと思うので、その辺りの確認もお願いします。
- ランキングページ：画面サイズによってページ崩れ・結果が一部ヘッダーの下に潜ってしまい隠れてしまうetc、修正箇所が散見されるので修正してください。
- メールアドレス登録とLINE登録で別ユーザーとして認識されてしまっているようなので、メールアドレス登録を廃止するか、メールアドレス登録後もLINEと紐付けられるようにしてください。
- LINE登録時にメールアドレスにLINEのメールアドレスがでてしまっています。望ましくないかと思うのでLINE登録の際は非表示にするなどしてください。
- メールアドレスのみの登録の場合、通知も特に無いですが、このサービスの根幹でもあるアラーム機能としてのサービスは果たせるかが疑問です。メールアドレスの登録は無くても良いかと思います。
- 独自ドメイン対応してください。
- LINEのアイコンを設定してください。
- 通知から公式URLに飛ぶのではなく、"アラーム通知のテキスト「時刻になりました」→ユーザーに何か特定な文字列を打ち込ませて投稿させる（スマホ操作している==起きた）→報酬の動画のURLをトーク上に表示する"の動線の方が望ましいかと思います。検討して修正してください。
- LINEトークから公式ページへ遷移した際にレスポンシブ対応ができていないためか白色の領域が表示されたり、ヘッダーが飛び出していたり、UIとして酷い状態にあるので整えてください。
- アラームの設定もLINE上から完結させるか、アラームの設定が無い場合は設定を促す通知を行うかなど対策を講じてください。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
1週間後を目処にレビューしますので、完了次第ご連絡ください。
よろしくお願いいたします。

**Comment by 39takagikouta** [comment]
ご対応ありがとうございます。
一週間後のレビューについても承知しました。
issueをクローズします
